services:
  # front:
  #   build: ./frontend/Dockerfile
  #   ports:
  #     - "3000:3000"

  # back:
  #   build: ./backend/Dockerfile
  #   ports:
  #     - "3001:3000"

  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=Tripz_S3cret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tripz_db

  # redis:
  #   image: "redis:alpine"
